directories:
  output: release
  buildResources: build
productName: AI Tickets
appId: com.AITickets.client
artifactName: '${productName}-${version}-${os}-${arch}-setup.${ext}'
win:
  target: nsis
  icon: build/icons/icon.png
files:
  - '**/*'
  - '!**/e2e/**/*'
  - '!**/src/**/*'
  - '!**/.angular-cli.json'
  - '!**/karma.conf.js'
  - '!**/protractor.conf.js'
  - '!**/tsconfig.json'
  - '!**/tslint.json'
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: true
electronVersion: 2.0.0
